### PR TITLE
someTweaks

### PR DESCRIPTION
**Pull request by Apricot-ale**
Add Japanese Localization
Add a copy of the "ACE_controlledUAV" definition postInit script. that loaded when there is no ACE.
Change requiredAddons to CBA from ACE.
Change requiredVersion to 2.14 from 2.10.
Revert "onEditChanged" with "onKeyUP". onEditChanged is looks not works good. (all settings force set to 12000m every time at open gui)

### CODE REVIEW

**Comment by Apricot-ale** [comment]
Closed and canceled PR. Behavior around the UAV was unexpected....
This may be a more complex requirement than I think....

**Comment by DomT602** [comment]
Hi @Apricot-ale, thanks for the PR - would you be interested in making the Japanese localisation as its own PR? As that'd still be useful.
Ref the onEditChanged bit - can you detail how you recreate the problem, the fact it resets to 12000m shouldn't be anything to do with the eventhandler of onEditChanged

**Comment by Apricot-ale** [comment]
https://github.com/DomT602/Doms-Arma-3-Mods/pull/11 post japanese.
I'll try some situation and post an issue that 12000m reset problem.

**Comment by Apricot-ale** [comment]
https://github.com/DomT602/Doms-Arma-3-Mods/issues/12

**Pull request closed without merging**
